services:
  - type: web
    name: clinic-automation-api
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRE
        value: 15m
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
